name: shrine
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  url_launcher: ^6.1.6
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/hotel/
    - assets/coding.json
